// Generated by DYPAI. Do not edit by hand.
// Source of truth: dypai/flows/*.flow.ts (preferred) or dypai/endpoints/*.yaml (legacy).
//
// This stub is replaced by `bun run dypai:generate-types` once real endpoints
// exist. While the project has zero backend endpoints, this open type lets
// `dypai.api.get(...)` calls compile; the moment endpoints are generated, the
// stricter named map narrows valid keys and exposes per-endpoint input/output.
import type { EndpointMap } from '@dypai-ai/client-sdk'

export type EndpointContracts = EndpointMap
